# Generated by Django 4.0.4 on 2022-05-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_card',
            field=models.BooleanField(default=False, verbose_name='card status'),
        ),
    ]
